### ISSUE TITLE
Error when importing Lib

### ISSUE THREAD

**Issue by UAproudaut** [CoolONEOfficial/NativePartialSheet#1]
If I import the lib in my existing project with import NativePartialSheet
I got the error : 
Ambiguous use of 'sheet(isPresented:onDismiss:content:)'

**Comment by CoolONEOfficial** [comment]
Most likely you need to be more explicit about the use of this method so that the compiler knows whether to use a sheet from the SwiftUI or from the NativePartialSheet

**Comment by Igorsnaki** [comment]
Same for me: 
After adding NativePartialSheet as SPM, all my existing .sheet methods return an error:
Ambiguous use of 'sheet(isPresented:onDismiss:content:)'
And project doesn't compile

**Comment by CoolONEOfficial** [comment]
Could you provide some example of incorrect behavior?
