### ISSUE TITLE
Adding NativePartialSheet affecting another custom view behaviour. 

### ISSUE THREAD

**Issue by Igorsnaki** [CoolONEOfficial/NativePartialSheet#4]
Hello, 

Thanks for lib. I added it to project for implementing some custom sheets. 

But recently I noticed that adding this either affects the work of another functionality.

I have custom ColorPicker (wrapper on UIKit : UIColorPickerViewController ) .
It worked  as expected , but after adding NativePartialSheet, my custom Color Picker start  dismissing when I choose a color. 

I found that, the following method is called: 

`struct NativePartialSheetView ->  func updateUIView(_ uiView: UIView, context: Context) -> 
107 line rootViewController.dismiss(animated: true)
`

<img width="1134" alt="Screenshot 2023-07-20 at 18 51 46" src="https://github.com/CoolONEOfficial/NativePartialSheet/assets/24248360/c1632170-a57d-471c-b6d9-3d81431915df">

I didn't call .sheet() methods and don't understand why it affects my ColorPicker code.
Do you have any ideas how to fix it? 

JFYI: if I comment .sheet code from NativePartialSheet lib or use the SwiftUI .sheet -> everything work as expected.

I made a demo project to reproduce the problem. Please find it here: 
https://www.dropbox.com/scl/fi/zntrv5xmv1nibp5hwskt7/PartialNativeSheetBugSampleCode.zip?rlkey=085b3dbcmutjf0w7r8hxi0t2h&dl=0

Looking forward to hearing from you . 
Thanks you in advance.

**Comment by CoolONEOfficial** [comment]
Hi, thanks for the clarification! I'll look into this issue when I have time 👌

**Comment by Igorsnaki** [comment]
@CoolONEOfficial did you have a chance to take a look at this issue?

**Comment by CoolONEOfficial** [comment]
Hey, yeah, but I haven't figured out how to fix it yet 😅 I'll dive deeper into this issue a little later on

**Comment by aehlke** [comment]
Another "complete" backport I found is https://github.com/ericlewis/PageSheet just sharing in case they have a solution that can be borrowed

**Comment by CoolONEOfficial** [comment]
Thanks for patience, fixed it in 2.0.5 👍
